###########
# site.title

title:    'Jekyll Starter Theme'
subtitle: 'Another Minimalistic Static Site Quick Starter Theme'
url: http://marhass.github.io


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
